# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lastdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Todo'),
        ),
    ]
